"""Main entry point for the lemma-level MIPVU to KG pipeline."""

from __future__ import annotations

import argparse
import copy
import os
from pathlib import Path
from typing import Any

try:
    from dotenv import load_dotenv
except ImportError:  # pragma: no cover - optional at runtime
    def load_dotenv(*_args: object, **_kwargs: object) -> bool:
        return False

from rdf.convert import convert_payload_to_turtle
from utils import read_json, read_text, write_json, write_text


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run legal metaphor annotation pipeline.")
    parser.add_argument("--input", type=Path, default=Path("data/input.txt"), help="Input legal text path.")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("data/output/graph_annotation.json"),
        help="Output annotation JSON path.",
    )
    parser.add_argument(
        "--pipeline",
        type=str,
        default="full",
        choices=["full"],
        help="Pipeline mode. Only the current full lemma MIPVU/KG pipeline is supported.",
    )
    parser.add_argument(
        "--prompt-dir",
        type=Path,
        default=Path("src/prompts"),
        help="Canonical prompt directory used by lemma sanity/contextual/MIPVU prompts.",
    )
    parser.add_argument("--ttl-output", type=Path, default=Path("data/output/metaphors.ttl"), help="RDF Turtle output path.")
    parser.add_argument(
        "--kg-output",
        type=Path,
        default=Path("data/output/metaphor_kg.ttl"),
        help="RDFLib KG serialization output path.",
    )
    parser.add_argument("--kg-format", type=str, default="turtle", help="RDFLib KG serialization format.")
    parser.add_argument("--kg-stats-output", type=Path, default=None, help="Optional KG stats JSON output path.")
    parser.add_argument("--document-id", type=str, default="", help="Optional document identifier.")
    parser.add_argument("--case-id", type=str, default="", help="Optional case identifier.")
    parser.add_argument("--pos-output", type=Path, default=Path("data/output/pos_nodes.json"))
    parser.add_argument("--corrected-output", type=Path, default=Path("data/output/pos_nodes_corrected.json"))
    parser.add_argument(
        "--contextual-json",
        type=Path,
        default=Path("data/output/pos_nodes_contextualized.json"),
        help="Path to contextualized POS JSON generated by preprocessing pipeline.",
    )
    parser.add_argument("--contextual-report-output", type=Path, default=None)
    parser.add_argument("--contextual-model", type=str, default="gpt-5.4-mini")
    parser.add_argument("--contextual-batch-size", type=int, default=100)
    parser.add_argument("--contextual-max-retries", type=int, default=3)
    parser.add_argument("--lemma-sanity-gpt", action="store_true", help="Use GPT in the full pipeline sanity stage.")
    parser.add_argument("--lemma-sanity-model", type=str, default="gpt-5.4-mini")
    parser.add_argument(
        "--dictionary-json",
        type=Path,
        default=Path("data/output/lemma_dictionary_lookup.json"),
        help="Path to lemma dictionary lookup JSON used by lemma MIPVU.",
    )
    parser.add_argument("--dictionary-page-size", type=int, default=None)
    return parser.parse_args()


def _load_contextual_meaning_lookup(path: Path) -> dict[str, str]:
    """Load contextual meaning lookup from contextualized JSON."""
    if not path.exists():
        return {}

    payload = read_json(path, default={})
    if not isinstance(payload, dict):
        return {}

    lemma_groups = payload.get("lemma_groups")
    if not isinstance(lemma_groups, list):
        return {}

    lookup: dict[str, str] = {}
    for group in [g for g in lemma_groups if isinstance(g, dict)]:
        lemma = str(group.get("lemma", "")).strip()
        if not lemma:
            continue
        contextual_meaning = str(group.get("contextual_meaning", "")).strip()
        if contextual_meaning:
            lookup[lemma] = contextual_meaning
    return lookup


def _configure_mipvu_input_paths(contextual_json: Path, dictionary_json: Path) -> None:
    """Point the lemma-level MIPVU node at the selected preprocessing outputs."""
    from nodes import mipvu_judge

    mipvu_judge.DEFAULT_CONTEXTUAL_JSON_PATH = contextual_json
    mipvu_judge.DEFAULT_DICTIONARY_LOOKUP_PATH = dictionary_json


def _llm_available() -> bool:
    return bool(os.getenv("OPENAI_API_KEY", "").strip())


def _stdict_available() -> bool:
    return bool(os.getenv("STDICT_API_KEY", "").strip())


def _contextual_fallback_payload(payload: dict[str, Any], reason: str) -> dict[str, Any]:
    """Attach a deterministic contextual_meaning placeholder when LLM contextualization is unavailable."""
    output = copy.deepcopy(payload)
    groups = output.get("lemma_groups", [])
    if not isinstance(groups, list):
        output["lemma_groups"] = []
        return output
    for idx, group in enumerate(groups):
        if not isinstance(group, dict):
            continue
        updated = dict(group)
        updated["contextual_meaning"] = str(group.get("contextual_meaning", "")).strip() or reason
        groups[idx] = updated
    return output


def _run_full_preprocessing(args: argparse.Namespace, input_text: str, document_id: str) -> tuple[dict[str, Any], list[str]]:
    """Run raw text preprocessing through contextual and dictionary JSON preparation."""
    errors: list[str] = []

    from preprocessing.dictionary_lookup import build_lemma_dictionary_lookup_payload
    from preprocessing.lemma_group_sanity import correct_pos_json_payload, infer_report_output_path
    from preprocessing.main import build_pos_json

    pos_payload = build_pos_json(input_text, document_id=document_id)
    write_json(args.pos_output, pos_payload)

    use_gpt_sanity = bool(args.lemma_sanity_gpt and _llm_available())
    if args.lemma_sanity_gpt and not _llm_available():
        errors.append("[full] OPENAI_API_KEY가 없어 lemma sanity GPT 단계를 local cleanup으로 대체했습니다.")
    corrected_payload, sanity_report = correct_pos_json_payload(
        pos_payload,
        use_gpt=use_gpt_sanity,
        prompt_dir=args.prompt_dir,
        model=args.lemma_sanity_model,
    )
    write_json(args.corrected_output, corrected_payload)
    write_json(infer_report_output_path(args.corrected_output), sanity_report)

    contextual_payload = corrected_payload
    contextual_source = "generated"
    if _llm_available():
        from preprocessing.contextual_meaning import (
            default_prompt_path,
            extract_contextual_meanings,
            infer_report_output_path as infer_contextual_report_output_path,
        )

        contextual_payload, contextual_report = extract_contextual_meanings(
            corrected_payload,
            prompt_path=default_prompt_path(),
            source_text=input_text,
            model=args.contextual_model,
            batch_size=args.contextual_batch_size,
            max_retries=args.contextual_max_retries,
        )
        write_json(args.contextual_json, contextual_payload)
        write_json(
            args.contextual_report_output or infer_contextual_report_output_path(args.contextual_json),
            contextual_report,
        )
    elif args.contextual_json.exists():
        loaded_contextual = read_json(args.contextual_json, default={})
        if isinstance(loaded_contextual, dict):
            contextual_payload = loaded_contextual
            contextual_source = "reused_existing_without_llm"
            errors.append(f"[full] OPENAI_API_KEY가 없어 기존 contextual JSON을 재사용했습니다: {args.contextual_json}")
        else:
            contextual_payload = _contextual_fallback_payload(
                corrected_payload,
                "WIDLII: OPENAI_API_KEY가 없어 문맥 의미를 새로 생성하지 못했습니다.",
            )
            write_json(args.contextual_json, contextual_payload)
            contextual_source = "fallback_without_llm"
    else:
        contextual_payload = _contextual_fallback_payload(
            corrected_payload,
            "WIDLII: OPENAI_API_KEY가 없어 문맥 의미를 새로 생성하지 못했습니다.",
        )
        write_json(args.contextual_json, contextual_payload)
        contextual_source = "fallback_without_llm"
        errors.append(f"[full] OPENAI_API_KEY가 없어 fallback contextual JSON을 생성했습니다: {args.contextual_json}")

    dictionary_source = "generated"
    if not _stdict_available() and args.dictionary_json.exists():
        dictionary_payload = read_json(args.dictionary_json, default={})
        if isinstance(dictionary_payload, dict):
            dictionary_source = "reused_existing_without_stdict_key"
            errors.append(f"[full] STDICT_API_KEY가 없어 기존 dictionary JSON을 재사용했습니다: {args.dictionary_json}")
        else:
            dictionary_payload = build_lemma_dictionary_lookup_payload(
                contextual_payload,
                source_path=args.contextual_json,
                page_size=args.dictionary_page_size,
            )
            write_json(args.dictionary_json, dictionary_payload)
            dictionary_source = "fallback_without_stdict_key"
    else:
        dictionary_payload = build_lemma_dictionary_lookup_payload(
            contextual_payload,
            source_path=args.contextual_json,
            page_size=args.dictionary_page_size,
        )
        write_json(args.dictionary_json, dictionary_payload)
        if not _stdict_available():
            dictionary_source = "fallback_without_stdict_key"

    metadata = {
        "preprocessing": {
            "pos_output": str(args.pos_output),
            "corrected_output": str(args.corrected_output),
            "contextual_json": str(args.contextual_json),
            "contextual_source": contextual_source,
            "dictionary_json": str(args.dictionary_json),
            "dictionary_source": dictionary_source,
            "pos_sentence_count": len(pos_payload.get("sentences", [])) if isinstance(pos_payload, dict) else 0,
            "pos_lemma_group_count": len(pos_payload.get("lemma_groups", [])) if isinstance(pos_payload, dict) else 0,
            "contextual_lemma_group_count": len(contextual_payload.get("lemma_groups", []))
            if isinstance(contextual_payload, dict)
            else 0,
            "dictionary_lemma_group_count": dictionary_payload.get("summary", {}).get("lemma_group_count", 0)
            if isinstance(dictionary_payload, dict)
            else 0,
        }
    }
    return metadata, errors


def _run_current_lemma_kg_pipeline(
    *,
    raw_text: str,
    document_id: str,
    case_id: str,
    contextual_json: Path,
    dictionary_json: Path,
    metadata: dict[str, Any] | None = None,
    initial_errors: list[str] | None = None,
) -> dict[str, Any]:
    """Run lemma-level MIPVU -> RDF/KG nodes."""
    from nodes.mipvu_judge import mipvu_judge_node
    from nodes.rdf_convert import rdf_convert_node
    from nodes.rdf_mapping import rdf_mapping_node
    from nodes.validation_check import validation_check_node
    from schemas.annotation import create_empty_state

    _configure_mipvu_input_paths(contextual_json, dictionary_json)
    contextual_meaning_by_lemma = _load_contextual_meaning_lookup(contextual_json)
    state = create_empty_state(document_id=document_id, case_id=case_id, raw_text=raw_text)
    state["contextual_meaning_by_lemma"] = contextual_meaning_by_lemma
    state["metadata"] = {
        "pipeline": "full",
        "prompt_directory": "src/prompts",
        "llm_available": _llm_available(),
        "contextual_meaning_lookup_available": bool(contextual_meaning_by_lemma),
        "contextual_meaning_lookup_size": len(contextual_meaning_by_lemma),
    }
    if metadata:
        state["metadata"].update(metadata)
    if initial_errors:
        state["errors"].extend(initial_errors)
    if not state["metadata"]["llm_available"]:
        state["errors"].append("[full] OPENAI_API_KEY가 없어 LLM 기반 MIPVU 판정은 fallback 결과를 반환할 수 있습니다.")

    for node in (mipvu_judge_node, rdf_mapping_node, validation_check_node, rdf_convert_node):
        result = node(state)
        state.update(result)
    state["status"] = state.get("status") or "completed"
    if state["status"] == "initialized":
        state["status"] = "completed"
    return state


def _write_kg_output_if_requested(payload: dict[str, Any], args: argparse.Namespace, *, default_for_full: bool) -> Path | None:
    kg_output = args.kg_output
    if kg_output is None and default_for_full:
        kg_output = args.output.with_name("metaphor_kg.ttl")
    if kg_output is None:
        return None

    from graph_build import graph_from_annotation_payload, graph_stats, serialize_graph

    graph = graph_from_annotation_payload(payload)
    serialize_graph(graph, kg_output, args.kg_format)
    stats = graph_stats(graph)
    if args.kg_stats_output:
        write_json(args.kg_stats_output, stats)
    payload.setdefault("metadata", {})["kg_output"] = str(kg_output)
    payload.setdefault("metadata", {})["kg_triple_count"] = stats["triple_count"]
    return kg_output


def _validation_status(payload: dict[str, Any]) -> str:
    results = payload.get("validation_results", [])
    if not isinstance(results, list):
        return "ok"
    for item in results:
        if not isinstance(item, dict):
            continue
        if item.get("repair_needed"):
            return "needs_repair"
        issues = item.get("issues", [])
        if isinstance(issues, list) and any(isinstance(issue, dict) and issue.get("severity") == "error" for issue in issues):
            return "needs_repair"
    return "ok"


def _normalize_graph_payload(
    state: dict[str, Any],
    *,
    pipeline: str,
    prompt_dir: Path,
    llm_available: bool,
) -> dict[str, Any]:
    metadata = dict(state.get("metadata", {}))
    metadata.update(
        {
            "pipeline": pipeline,
            "official_pipeline": True,
            "prompt_directory": str(prompt_dir),
            "llm_available": llm_available,
        }
    )
    validation_status = _validation_status(state)
    metadata["validation_status"] = validation_status
    payload = {
        "document_id": state.get("document_id", ""),
        "case_id": state.get("case_id", ""),
        "mipvu_annotations": state.get("mipvu_annotations", []),
        "rdf_mappings": state.get("rdf_mappings", []),
        "validation_results": state.get("validation_results", []),
        "human_review_items": state.get("human_review_items", []),
        "rdf_output": state.get("rdf_output", ""),
        "errors": list(state.get("errors", [])),
        "metadata": metadata,
        "status": "needs_repair" if validation_status == "needs_repair" else state.get("status", "completed"),
    }
    if not llm_available and not any("OPENAI_API_KEY" in str(item) for item in payload["errors"]):
        payload["errors"].append("[main] OPENAI_API_KEY가 없어 full pipeline의 LLM 단계가 빈 결과 또는 fallback 결과를 반환했습니다.")
    return payload


def main() -> None:
    load_dotenv()
    args = parse_args()
    input_text = read_text(args.input)
    document_id = args.document_id or args.input.stem
    case_id = args.case_id
    llm_available = _llm_available()

    kg_output_path: Path | None = None

    preprocessing_metadata, preprocessing_errors = _run_full_preprocessing(args, input_text, document_id)
    state = _run_current_lemma_kg_pipeline(
        raw_text=input_text,
        document_id=document_id,
        case_id=case_id,
        contextual_json=args.contextual_json,
        dictionary_json=args.dictionary_json,
        metadata=preprocessing_metadata,
        initial_errors=preprocessing_errors,
    )
    output_payload = _normalize_graph_payload(
        state,
        pipeline=args.pipeline,
        prompt_dir=args.prompt_dir,
        llm_available=llm_available,
    )

    if args.ttl_output:
        if not output_payload.get("rdf_output"):
            output_payload["rdf_output"] = convert_payload_to_turtle(
                output_payload, output_payload.get("validation_results", [])
            )
        write_text(args.ttl_output, str(output_payload.get("rdf_output", "")))

    kg_output_path = _write_kg_output_if_requested(
        output_payload,
        args,
        default_for_full=args.pipeline == "full",
    )

    write_json(args.output, output_payload)
    print(f"[main] pipeline={args.pipeline} status={output_payload.get('status', 'completed')}")
    print(f"[main] saved: {args.output}")
    if args.ttl_output:
        print(f"[main] ttl saved: {args.ttl_output}")
    if kg_output_path:
        print(f"[main] kg saved: {kg_output_path}")


if __name__ == "__main__":
    main()
